# Generated by Django 3.0.2 on 2020-02-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_load_data_20200203_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Province',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Region',
            new_name='County',
        ),
    ]
