# Generated by Django 3.0.2 on 2020-03-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_load_data_20200213_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='code'),
        ),
    ]
