# Generated by Django 3.0.2 on 2020-04-02 21:07

from django.db import migrations
from places.loader import Loader


def load_peru_data(apps, schema_editor):
    """
    Function that loads the data
    """

    loader = Loader()
    loader.load_peru()
    loader.load_countries()

def reverse_load_peru_data(apps, schema_editor):
    """
    Function that reverse load_data function deleting Country instances.
    It also will delete regions, provinces and districts.
    """

    Country = apps.get_model("places", "Country")
    db_alias = schema_editor.connection.alias
    Country.objects.using(db_alias).delete()


def load_ubigeo_district(apps, schema_editor):
    """
    Function that updates districts with their ubigeo.
    """

    District = apps.get_model('places', 'District')
    districts = District.objects.all()
    for district in districts:
        district.ubigeo = (
                district.city.county.code + district.city.code + district.code)
        district.save()


def reverse_load_ubigeo_district(apps, schema_editor):
    """
    Function that reverse load_data function deleting ubigeo of District model.
    """

    District = apps.get_model('places', 'District')
    districts = District.objects.all()
    for district in districts:
        district.ubigeo = ''
        district.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_district_ubigeo'),
    ]

    operations = [
        migrations.RunPython(load_peru_data, reverse_load_peru_data),
        migrations.RunPython(load_ubigeo_district, reverse_load_ubigeo_district),
    ]
