# Generated by Django 3.0.2 on 2021-02-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_data_load_ubigeo_20200402_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='code'),
            preserve_default=False,
        ),
    ]
